version: '2'

services:
    db:
        image: mysql
        ports:
            - "3311:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./docker/php-fpm
        ports:
            - "9001:9000"
        #volumes:
        #    - ./symfony:/var/www/symfony:cached
        #    - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - db
    nginx:
        build: ./docker/nginx
        ports:
            - "81:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    elk:
        image: willdurand/elk
        ports:
            - "82:80"
        volumes:
            - ./docker/elk/logstash:/etc/logstash:cached
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns:cached
        volumes_from:
            - php
            - nginx
    react-app:
        container_name: react-app
        build:
          context: .
          dockerfile: ./docker/react/Dockerfile
        volumes:
          - '.:/usr/src/app'
          - '/usr/src/app/node_modules'
        ports:
          - '3000:3000'
        environment:
          - NODE_ENV=development
